### PR TITLE
Add:  updateSelfClaimMembership function

### PR DESCRIPTION
**Pull request by Rashmi-278**
Dependent PR's:
https://github.com/cvoxelprotocol/vess/pull/25

### CODE REVIEW

**Comment by kitakaze-kan** [comment]
Thanks @Rashmi-278 ! I don't know cuz I haven't tried it yet, but is it working correctly with pnpm?

**Comment by Rashmi-278** [comment]
> Thanks @Rashmi-278 ! I don't know cuz I haven't tried it yet, but is it working correctly with pnpm?

No Actually, facing some build errors. We need to also migrate SDK to pnpm

**Comment by kitakaze-kan** [comment]
@Rashmi-278 got it! thanks. okay, in that case, can you use yarn for this PR? I am going to migrate pnpm ASAP just after we merge it

**Review by kitakaze-kan — CHANGES_REQUESTED** [review]
can you use Yarn for this change?

**Comment by Rashmi-278** [comment]
Yes yes, sorry for the late reply, I am using that, and I am facing build errors with typescript types, solved a few, one remaining
lIke,
image

**Comment by kitakaze-kan** [comment]
> Yes yes, sorry for the late reply, I am using that, and I am facing build errors with typescript types, solved a few, one remaining lIke, image

thanks! does this error still happen in yarn? I would like to use pnpm if possible, but we have not yet figured out the full extent of the impact, so I would prefer not to change the package manager in order to release this change quickly.

**Comment by Rashmi-278** [comment]
Yes actually, it happens in Yarn too, I'm using Yarn for this now.

**Comment by kitakaze-kan** [comment]
omg okay, I am checking

**Comment by kitakaze-kan** [comment]
@Rashmi-278 I found the cause here. It was due to an update of @ceramicnetwork/common (FYI: https://github.com/ceramicnetwork/js-ceramic/pull/2750 ). I don't think there is any scope of impact, could you please remove `pin:true` ?
Also, I will perform the publish of the sdk and will let you know when I merge and release the sdk. thanks!

スクリーンショット 2023-07-11 17 57 40

**Comment by Rashmi-278** [comment]
Yes Thank you! I thought so too! I found it here https://developers.ceramic.network/reference/stream-programs/tile-document/

**Comment by Rashmi-278** [comment]
> @Rashmi-278 I found the cause here. It was due to an update of @ceramicnetwork/common (FYI: [ceramicnetwork/js-ceramic#2750](https://github.com/ceramicnetwork/js-ceramic/pull/2750) ). I don't think there is any scope of impact, could you please remove `pin:true` ? Also, I will perform the publish of the sdk and will let you know when I merge and release the sdk. thanks!
> 
> スクリーンショット 2023-07-11 17 57 40

Thank you so much ! and sure !

**Review by kitakaze-kan — APPROVED** [review]
LGFM!

**Pull request merged**
